### ISSUE TITLE
[v0.2] Permission error with Cutout.prepare() on Windows.

### ISSUE THREAD

**Issue by euronion** [FRESNA/atlite#22]
*Occuring in new version branch v0.2*

## Code
When running the standard pattern for creating a ERA5 cutout (see examples/create_cutout.py):
```
cutout = atlite.Cutout(name="europe-2011-01",
                                      module="era5",
                                       xs=slice(-12.18798349, 41.56244222),
                                       ys=slice(71.65648314, 33.56459975),
                                       years=slice(2011, 2011),
                                       months=slice(1,1))
```

## Exception
I get this exception when atlite tries to delete the temporary files downloaded for creating the cutout:

> INFO:atlite.datasets.common:Deleting file C:\Users\<User>\AppData\Local\Temp\tmpmsdmnmk8.nc
> Exception ignored in: <finalize object at 0x25f484f2850; dead>
> Traceback (most recent call last):
>   File "C:\anaconda\envs\atlite\lib\weakref.py", line 548, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\<User>\Documents\GitHub\atlite\atlite\datasets\common.py", line 19, in noisy_unlink
>     os.unlink(path)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<User>\\AppData\\Local\\Temp\\tmpmsdmnmk8.nc'

The error occurs multiple times for all the temp files created. They are not properly cleaned up.

## Plattform
* Windows 10 (haven't tested it on Linux yet)
* Python 3.6.6

## Related lines of code

Should be related to the new way of handling the files with:

https://github.com/FRESNA/atlite/blob/6f3559d5e20a05c79fa55596623c732930581178/atlite/datasets/common.py#L17-L19

and

*-unrelated line of code removed-*

**Comment by coroa** [comment]
Ah ok, it's clear why that happens. Windows puts locks on all open files, so that one cannot delete or actually even read from an already open file and i'm trying to delete the temporary files seemingly at a point in time, when the libnetcdf library used by xarray hasn't released them just yet. Instead i will have to schedule deletion somehow and then only execute them a tiny bit later. Will not affect linux or macos as they don't use these locks.

Will have to experiment a bit.

**Comment by euronion** [comment]
*Update on tracking down the problem:*

The PermissionError pops up at this point, where merging of the different feature datasets happens:

https://github.com/FRESNA/atlite/blob/6f3559d5e20a05c79fa55596623c732930581178/atlite/data.py#L163

Then the `weakref.finalize(...)` is triggered calling the unlink. At first I thought that was too early, but then I figured we just have to close the `xarray.Dataset` properly... .
I'll create a PR in a moment.

**Comment by coroa** [comment]
the whole point of the finalizer was to delete the file automatically after `xarray` itself decides it's time to close the file. So closing it yourself kind of defeats the purpose (even if it works in this particular case). I dug a bit deeper into `xarray`s code and found that it is always using a `(Caching)FileManager` to handle cleaning up of open files, and thus moved the finalizer there. So that as soon as the filemanager handling the file is garbage collected the finalizer is called and deletes the file. I just pushed the code (https://github.com/FRESNA/atlite/pull/20/commits/f3ab9b0e6ce7d9b936a6df5aeec626c8f38e8b63). It works fine in a Win7 virtualbox for me.
